### ISSUE TITLE
'가입하기'와 '도전과제 활성화하기' 도전과제 만들기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/AchievementBadges#2]
|              | 가입하기                                           | 도전과제 활성화하기                                                                                       |
| ------------ | -------------------------------------------------- | --------------------------------------------------------------------------------------------------------- |
| 등록         | 도전과제가 베타기능이 아닐 때                      | 도전과제가 베타기능일 때                                                                                  |
| 달성         | 유저가 가입했을 때                                 | 유저가 도전과제를 활성화했을 때                                                                           |
| 검사         | 무조건 참                                          | 무조건 참                                                                                                 |
| 달성 전 힌트 | [[특수:계정만들기&vert;{{SITENAME}}에 가입]]하세요 | [[특수:환경설정#mw-prefsection-betafeatures&vert;환경 설정의 베타 기능]]에서 도전과제 뱃지를 활성화하세요 |
| 달성 후 내용 | 당신은 페미위키의 기여자가 되었습니다!             | 도전과제 뱃지 베타 기능을 활성화했습니다! 베타 기간 동안 어쩌구 주의사항에 주의하세요.                              |

등록: 해당 도전과제가 사이트에 도전과제로 표시될 지 여부, 등록되지 않으면 아예 없는 도전과제 취급됨
달성: 어떤 Hook에서 어떤 조건을 검사할지 그 내용
검사: 특정 시점에서 해당 도전과제가 달성됐는지를 확인하여야 할 때(예를 들어 1. 도전과제 확장기능이 방금 설치됐거나, 2. 베타기능을 활성한 직후거나, 3. 달성이 누락되어 관리자가 따로 요청할 때 등에) 검사할 방법.

**Comment by love-adela** [comment]
우왕 무슨 Mediawiki 사용해서 기능 추가하는건가용?

**Comment by lens0021** [comment]
네네 이 리포에서 도전과제를 제공하는 미디어위키 확장기능을 만들고 있습니다
