### ISSUE TITLE
AchievementBadges requires Echo to be installed

### ISSUE THREAD

**Issue by InVinCiblezz** [femiwiki/AchievementBadges#7]
Uncaught ExtensionDependencyError: AchievementBadges requires Echo to be installed

**Comment by lens0021** [comment]
[Echo](https://www.mediawiki.org/wiki/Extension:Echo) is an extension that is bundled in MediaWiki, could you try adding the next line in your [LocalSettings.php](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:LocalSettings.php)?
```php
wfLoadExtension( 'Echo' );
```
Or, did you mean that AchievementBadges requires Echo unnecessarily? Well, AchievementBadges w/o Echo makes sense some little, although it provides just a special page. I am willing to create a patch for it.

**Comment by InVinCiblezz** [comment]
Thanks for your quick response!
I use MediaWiki 1.35.1 and it looks like Echo is not bundled in it.
I will try to install it and run updated.php. 
Then, it works. 
Happy holidays!
